mirrorJSRequire=function e$$0(q,k,h){function l(d,m){if(!k[d]){if(!q[d]){var e="function"==typeof mirrorJSRequire&&mirrorJSRequire;if(!m&&e)return e(d,!0);if(a)return a(d,!0);throw Error("Cannot find module '"+d+"'");}e=k[d]={exports:{}};q[d][0].call(e.exports,function(a){var b=q[d][1][a];return l(b?b:a)},e,e.exports,e$$0,q,k,h)}return k[d].exports}for(var a="function"==typeof mirrorJSRequire&&mirrorJSRequire,d=0;d<h.length;d++)l(h[d]);return l}({"./base":[function(n,q,k){q.exports=n("Vlbn99")},{}],
Vlbn99:[function(n,q,k){var h=n("./baseHTMLDefaults"),l=n("./logger");k.ui=function(a,d,g,m){var e=this;this.ui=a;this.parent=g;this.handle=d;this.type="";this.events={};this.activeEvents={};this.create=function(){var a;a=void 0!==this.parent?this.parent.getContainerNodeForChild(this,m):m&&m.ParentElement?$(m.ParentElement):$(document.body);this.node_cnt$=this.drawContainer(a);this.decoratingContainer&&this.decoratingContainer();this.show()};this.show=function(){};this.getContainerNodeForChild=function(a,
f){return this.node_cnt$};var c={Position:function(a){e.setPosition(a)},Top:function(a){e.setTop(a)},Left:function(a){e.setLeft(a)},Width:function(a){e.setWidth(a)},Height:function(a){e.setHeight(a)},Visible:function(a){e.setVisible(a)},Disabled:function(a){e.setDisabled(a)},Color:function(a){e.setColor(a)},Border:function(a){e.setBorder(a)}};this.parseState=function(b){for(var f in b){void 0!==this.props&&void 0!==this.props[f]&&void 0!==this.props[f].set?this.props[f].set.call(this,b[f]):void 0!==
c[f]&&c[f].call(this,b[f]);var g=f;"Width"===g||"Height"===g?(e.afterResize&&e.afterResize(),a.events.fire(d,"widgetResize")):"Top"!==g&&"Left"!==g||a.events.fire(d,"widgetMove")}};this.destroy=function(){this.beforeDestroy&&this.beforeDestroy();this.node_cnt$.remove();this.afterDestroy&&this.afterDestroy()};this.activateEvent=function(a,f){f?(this.activeEvents[a]=!0,l.log("Frontend: Activating event "+a+" ["+d+"]",l.level.LOG_EVENTS)):this.activeEvents[a]&&(delete this.activeEvents[a],l.log("Frontend: Deactivating event "+
a+" ["+d+"]",l.level.LOG_EVENTS))};this.addClass=function(a){this.node_cnt$.addClass(a)};this.removeClass=function(a){this.node_cnt$.removeClass(a)};this.focus=function(){this.node$&&this.node$.focus()};this.__internal_events={__focus:this.focus};var b={keyboard:h.mixins.keyboard};this.loadMixin=function(a,f){b[a]&&b[a].call(this,f)};h.core.call(this)};k.backend=function(a,d,g,h){var e=this;this.handle=d;this.parent=g;this.children={};var c="",b={};this.events={};var p={};this.parseProps=function(f){for(var b in f)(function(f,
b,c){var e={};if(void 0!==c.get&&void 0!==c.set)e.get=c.get,e.set=c.set;else if(void 0!==c["default"])p[b]=c["default"],e.get=function(){return p[b]},e.set=function(a){return p[b]=a};else{console.log("Invalid property setting for ["+b+"]");return}var d=c.type;Object.defineProperty(f,b,{get:e.get,set:function(r){r=e.set(r);void 0!==d&&("int"===d?(r=parseInt(r),isNaN(r)&&(r=c["default"])):"float"===d?(r=parseFloat(r),isNaN(r)&&(r=c["default"])):"boolean"===d&&!0!==r&&!1!==r&&(r=c["default"]));a.setState(f.handle,
b,r)}})})(e,b,f[b])};this.mapChildren=function(f,b){for(var c in this.children){var e=a.getWidget(c);f(e);!0===b&&e.mapChildren(f,!0)}};this.destroy=function(){a.fireEvent(this.handle,"destroy");a.unregisterWidgetName(c);a.destroy(this.handle)};this.on=function(f,c){l.log("Backend: Binding event "+f+" ["+d+"]",l.level.LOG_EVENTS);b[f]=c;a.events.activate(this.handle,f,!0)};this.off=function(f){l.log("Backend: Unbinding event "+f+" ["+d+"]",l.level.LOG_EVENTS);b[f]=void 0;a.events.activate(this.handle,
f,!1)};this.getCustomEventHandler=function(a){return b[a]};this.getState=function(){return a.getState(this.handle)};this.addClass=function(f){a.domClassHandler(this.handle,f,!0)};this.focus=function(){a.events.fire(d,"__focus")};this.removeClass=function(f){a.domClassHandler(this.handle,f,!1)};this.__base_props={Name:{get:function(){return c},set:function(f){if(!0===a.registerWidgetName(f,d)||""===f)a.unregisterWidgetName(c),c=f;return c},description:"The Name property specifies the name of the widget."},
Position:{"default":"",description:"The Position property specifies the type of positioning method used for the widget (static, relative, absolute, fixed (or more if implemented by the frontend))."},Top:{"default":0,type:"int",description:"For absolutely positioned widgets, the Top property sets the top edge of the widget to a unit above/below the top edge of its containing widget. For relatively positioned widgets, the Top property sets the top edge of the widget to a unit above/below its normal position."},
Left:{"default":0,type:"int",description:"For absolutely positioned widgets, the Left property sets the left edge of the widget to a unit to the left/right of the left edge of its containing widget. For relatively positioned widgets, the Left property sets the left edge of the widget to a unit to the left/right to its normal position."},Width:{"default":0,type:"int",description:"The Width property sets the width of the widget."},Height:{"default":0,type:"int",description:"The Height property sets the height of the widget."},
Visible:{"default":!0,type:"boolean",description:"The Visible property sets the visibility of the widget."},Disabled:{"default":!1,type:"boolean",description:"The Disabled property sets or returns whether an element is disabled, or not."},Color:{"default":"",description:"The Color property sets the text color of the widget."},Border:{"default":"",description:"The Border property sets the style, size and color of a widget's border."}};this.parseProps(this.__base_props)}},{"./baseHTMLDefaults":3,"./logger":7}],
3:[function(n,q,k){q.exports={core:function(){this.drawContainer=function(h){h.append('<div id="'+this.handle+'"></div>');return $("#"+this.handle,h)};this.decoratingContainer=function(){this.node_cnt$.addClass("mirrorJSWidget");this.node_cnt$.addClass("mirrorJS_"+this.type)};this.setPosition=function(h){this.node_cnt$.css("position",h)};this.setTop=function(h){this.node$&&this.node_cnt$.css("top",h+"px")};this.setLeft=function(h){this.node$&&this.node_cnt$.css("left",h+"px")};this.setWidth=function(h){this.node$&&
this.node$.css("width",h+"px")};this.setHeight=function(h){this.node$&&this.node$.css("height",h+"px")};this.setVisible=function(h){this.node_cnt$&&this.node_cnt$.css("visibility",h?"":"hidden")};this.setDisabled=function(h){this.node$&&(this.node$.attr("disabled",h),h?this.node$.addClass("mirrorJS_disabled"):this.node$.removeClass("mirrorJS_disabled"))};this.setColor=function(h){this.node$&&this.node$.css("color",h)};this.setBorder=function(h){this.node$&&this.node$.css("border",h)}},mixins:{keyboard:function(h){function l(a){return{altKey:a.altKey,
charCode:a.charCode,ctrlKey:a.ctrlKey,keyCode:a.keyCode,metaKey:a.metaKey,shiftKey:a.shiftKey,timeStamp:a.timeStamp,type:a.type,which:a.which}}this.bindKeyboardEvents=function(a){a.keyup(function(a){h("keyup",a,l(a))});a.keydown(function(a){h("keydown",a,l(a))});a.keypress(function(a){h("keypress",a,l(a))})}}}}},{}],4:[function(n,q,k){k.SockJS=function(h){var l=null,a=!1,d="",g=h.host,m=h.port||80,e=h.protocol;this.connect=function(c,b,p){void 0===e&&(e="http:");l=new SockJS(e+"//"+g+":"+m+"/mirror");
l.onopen=function(){a=!0;c()};l.onmessage=function(a){var c="";d+=a.data;"\n"===d.substr(-1)?(c=d,d=""):(a=d.split("\n"),d=a.pop(),c=a.join("\n"));b(c)};l.onclose=function(b){a=!1;p(b)}};this.send=function(c){a&&l&&l.send(c)};this.close=function(){a&&l&&l.close()}};k.Socket=function(h){var l=require("net"),a=null,d=!1,g="",m=h.host,e=h.port;this.connect=function(c,b,p){a=new l.Socket;a.connect(e,m,function(){d=!0;c()});a.on("data",function(a){var c="";g+=a.toString();"\n"===g.substr(-1)?(c=g,g=""):
(a=g.split("\n"),g=a.pop(),c=a.join("\n"));b(c)});a.on("close",function(a){d=!1;p(a)})};this.send=function(c){d&&a&&a.write(c)};this.close=function(){d&&sock&&sock.close()}}},{}],5:[function(n,q,k){var h=n("./logger");q.exports=function(l){this.fire=function(a,d,g,m){var e=l.getCtl(a);e&&(!0===m||e.activeEvents[d])&&(m={a:"e",t:d,w:a},void 0!==g&&(m.p=g),h.log("Frontend: Firing event "+d+" ["+a+"]",h.level.LOG_EVENTS),l.protocolHandler.handle([m]))};this.trigger=function(a,d,g){l.handleEvent({w:a,
t:d,p:g})}}},{"./logger":7}],6:[function(n,q,k){var h=n("./widgets"),l=n("./base"),a=n("./logger");q.exports=function(d){var g={},m=1,e={},c=null,b=this,p=!1;this.fireEvents=!0;this.prefixID="";this.exit=function(){this.disableBuffering(!0);this.destroyAll();setTimeout(d.close,50)};this.create=function(b,c,f){1E6<m&&(m=1);var e=this.prefixID+m++,d=h.getClass(b);a.log("Backend: Creating widget "+b+" ["+e+"]",a.level.LOG_DEBUG);if(void 0===d)a.log("Backend ERROR: The widget "+b+" ["+e+"] is not installed!!!",
a.level.LOG_INFO+a.level.LOG_DEBUG);else{var p=new l.backend(this,e,c,f);p.type=b;d.backend.call(p,this,e,c,f);void 0!==p.props&&p.parseProps(p.props);if(p&&p.isGoodParent&&!1==p.isGoodParent())a.log("Backend ERROR: The widget "+b+" ["+e+"] cannot be child of ["+g[c.handle].t+"]!!!",a.level.LOG_INFO+a.level.LOG_DEBUG);else if(c&&c.isGoodChild&&!1==c.isGoodChild(p))a.log("Backend ERROR: The widget "+b+" ["+e+"] cannot be child of ["+g[c.handle].t+"]!!!",a.level.LOG_INFO+a.level.LOG_DEBUG);else return g[e]=
{c:p,a:f,t:b,s:{}},void 0===f&&(f={}),b={a:"c",t:b,w:e,e:f},c&&void 0!==c.handle&&(b.p=c.handle,c.children&&(c.children[e]=p)),this.send(b),p}};var f={};this.checkWidgetName=function(a){return""!==a&&void 0===f[a]?!0:!1};this.registerWidgetName=function(b,c){var e=this.getWidget(c);if(this.checkWidgetName(b)&&e)return f[b]=e,!0;""!==b&&a.log("Backend: Invalid widget name ["+b+"]",a.level.LOG_INFO+a.level.LOG_DEBUG);return!1};this.unregisterWidgetName=function(a){""!==a&&delete f[a]};this.getWidgetByName=
function(a){if(""!==a)return f[a]};this.destroy=function(b){if(g[b]){var c=g[b].c;a.log("Backend: Destroying widget "+g[b].t+" ["+b+"]",a.level.LOG_DEBUG);delete g[b];if(c&&c.children)for(var f in c.children)c.children[f].destroy();c.parent&&c.parent.children&&delete c.parent.children[b];this.send({a:"d",w:b})}};this.destroyAll=function(){for(var a in g)this.destroy(a)};this.getWidget=function(a){if(g[a])return g[a].c};this.disableBuffering=function(b){!0===b?(a.log("Backend: Disabling buffering...",
a.level.LOG_DEBUG),p=!0,this.flushState()):(a.log("Backend: Enabling buffering...",a.level.LOG_DEBUG),p=!1)};this.getState=function(a){return void 0!==a&&g[a]?g[a]:{}};this.setState=function(b,f,d){void 0!==g[b]&&(g[b].s[f]=d,!0===this.fireEvents&&(a.log("Backend: Setting widget ["+b+"] state: ("+f+": "+d+")",a.level.LOG_DEBUG),void 0===e[b]&&(e[b]={}),e[b][f]=d,!0===p?this.flushState():(clearTimeout(c),c=setTimeout(this.flushState,5))))};this.flushState=function(){a.log("Backend: Flushing state...",
a.level.LOG_DEBUG);for(w in e)b.send({a:"u",w:w,s:e[w]});e={}};var k=[],n=null;this.send=function(a){k.push(a);!0===p?this.flushBuffer():(clearTimeout(n),n=setTimeout(this.flushBuffer,5))};this.flushBuffer=function(){a.log("Backend: Sending state...",a.level.LOG_DEBUG);d.handle(k);k=[]};this.fireEvent=function(c,f,e){var d=g[c];if(d&&d.c){d.c.events[f]&&(a.log("Backend: Firing internal event "+f+" ["+c+"]",a.level.LOG_EVENTS),d.c.events[f].call(d.c,d.c,e));var p=d.c.getCustomEventHandler(f);p&&(a.log("Backend: Firing event "+
f+" ["+c+"]",a.level.LOG_EVENTS),p.call(d.c,d.c,e));"widgetResize"===f&&d.c.mapChildren(function(a){b.fireEvent(a.handle,"parentWidgetResize",{parentWidgetInstance:d.c})},!0)}};this.events={fire:function(a,c,f){a={a:"E",t:c,w:a};void 0!==f&&(a.p=f);b.send(a)},activate:function(a,c,f){b.send({a:"A",t:c,w:a,p:f})}};this.domClassHandler=function(a,c,f){b.send({a:"wc",t:!0===f?"a":"r",w:a,p:c})};var q={},s=0;this.frontend={getProp:function(a,c,f,e){s++;1E6<s&&(s=0);q[s]=f;b.send({a:"fp",t:c,w:a,p:e,r:s})}};
this.handleFrontendProp=function(a,b,c,f){if((a=g[a])&&a.c&&q[b]){var e=!1;1===c&&(e=!0);q[b].call(a.c,a.c,e,f)}q[b]&&delete q[b]};var t=null;this.broadcast={send:function(a,b,c){console.log("0x90 NOP")},onmessage:function(a){t=a},trigger:function(a,b,c){null!==t&&t(a,b,c)}};var u={};this.emit=function(a,c){b.send({a:"m",t:a,w:c})};this.on=function(b,c){a.log("Backend: Binding custom event "+b,a.level.LOG_EVENTS);u[b]=c};this.triggerCustomEvent=function(a,b){if(void 0!==u[a])u[a](a,b)}}},{"./base":"Vlbn99",
"./logger":7,"./widgets":"RD6lrm"}],7:[function(n,q,k){var h=0;k.level={LOG_INFO:1,LOG_DEBUG:2,LOG_EVENTS:4,LOG_SOCKET:8};k.log=function(l,a){if(0!==(a&h)){var d=new Date,d=d.getHours()+":"+d.getMinutes()+":"+d.getSeconds()+":"+d.getMilliseconds()+" :: ";console.log(d+l)}};k.setDebugLevel=function(l){h=l}},{}],mirrorJS:[function(n,q,k){q.exports=n("N1UtQB")},{}],N1UtQB:[function(n,q,k){var h=n("./iApp"),l=n("./protocol"),a=n("./logger");q={MAJOR:0,MINOR:2,REVISION:1};k.VERSION=q.MAJOR+"."+q.MINOR+
"."+q.REVISION;k.servers=n("./servers");var d=function(d,m,e,c){d=new l(d,this);this.app=new h(d);d.attachApplicationInterface(this.app);void 0===e&&(e={});e.widgets&&e.widgets.prefixID&&(this.app.prefixID=e.widgets.prefixID);this.applicationID=0;this.parseRequests=function(b){a.log("Backend: Parsing protocol...",a.level.LOG_DEBUG);switch(b.a){case "u":break;case "e":this.app.fireEvent(b.w,b.t,b.p);break;case "Fp":this.app.handleFrontendProp(b.w,b.r,b.s,b.p);break;case "m":this.triggerCustomEvent(b.t,
b.w);break;default:console.log("parseRequests ",b)}};var b=new m(this.app,e.args);this.onClose=function(){if(void 0!==b.onClose)b.onClose();if(e.events&&void 0!==e.events.onClose)e.events.onClose(this.app)};this.onError=function(){if(void 0!==b.onError)b.onError();if(e.events&&void 0!==e.events.onError)e.events.onError(this.app)};var p={};!0===c?(this.on=function(b,c){a.log("Fontend: Binding custom event "+b,a.level.LOG_EVENTS);p[b]=c},this.emit=function(a,b){this.app.triggerCustomEvent(a,b)},this.triggerCustomEvent=
function(a,b){if(void 0!==p[a])p[a](a,b)}):(this.on=this.app.on,this.emit=this.app.emit,this.triggerCustomEvent=this.app.triggerCustomEvent)};k.app={};k.app.local=function(a,h,e){return new d(a,h,e,!0)};k.app.server=function(a,h,e){return new d(a,h,e,!1)};k.app.remote=function(d,m,e){var c=new l(d,this),b=new h(c);c.attachApplicationInterface(b);d.connection.connect(function(){d.connection.send('{"a":"x","w":"'+m+'"}\n');if(e&&e.onConnect)e.onConnect()},function(a){c.handle(a.split("\n").map(function(a){if(0<
a.length)return JSON.parse(a)}))},function(a){c.close();if(e&&e.onClose)e.onClose(a)});var p={};this.on=function(b,c){a.log("Fontend: Binding custom event "+b,a.level.LOG_EVENTS);p[b]=c};this.emit=function(a,b){var e=JSON.stringify({a:"m",t:a,w:b})+"\n";c.send(e)};this.triggerCustomEvent=function(a,b){if(void 0!==p[a])p[a](a,b)}};k.widgets={controller:n("./widgets"),base:n("./base")};k.connectors=n("./connectors");k.ui=n("./ui");k.logger=n("./logger");console.log("mirrorjs v"+k.VERSION)},{"./base":"Vlbn99",
"./connectors":4,"./iApp":6,"./logger":7,"./protocol":"D5yDcg","./servers":12,"./ui":13,"./widgets":"RD6lrm"}],D5yDcg:[function(n,q,k){var h=n("./ui"),l=n("./logger");q.exports=function(a,d){var g=this,m=new h.handler(this,a.name);this.handle=function(e){a.isRemote?this.send(e.map(function(a){return JSON.stringify(a)}).join("\n")+"\n"):e.map(function(c){if(c)switch(l.log("Fontend: Parsing protocol...",l.level.LOG_DEBUG),c.a){case "c":m.create(c);break;case "d":m.destroy(c.w);break;case "u":m.update(c);
break;case "A":m.activateEvent(c);break;case "E":m.handleEvent(c);break;case "e":!1==a.isRemote&&a.connection?(c=JSON.stringify(c)+"\n",g.send(c)):g.iApp.fireEvent(c.w,c.t,c.p);break;case "wc":m.domClassHandler(c.w,c.p,"a"===c.t?!0:!1);break;case "fp":m.getFrontendProp(c.w,c.t,c.p,c.r);break;case "Fp":!1==a.isRemote&&a.connection?(c=JSON.stringify(c)+"\n",g.send(c)):g.iApp.handleFrontendProp(c.w,c.r,c.s,c.p);break;case "m":d.triggerCustomEvent(c.t,c.w);break;default:console.log("Protocol Error!!! ",
c)}})};this.iApp=void 0;this.attachApplicationInterface=function(a){this.iApp=a};this.close=function(){m.destroyAll();void 0!==a.connection&&void 0!==a.connection.close&&a.connection.close()};this.send=function(e){void 0!==a.connection&&(l.log("Fontend: Sending ["+e.length+" bytes]...",l.level.LOG_SOCKET+l.level.LOG_DEBUG),a.connection.send(e))}}},{"./logger":7,"./ui":13}],"./protocol":[function(n,q,k){q.exports=n("D5yDcg")},{}],12:[function(n,q,k){function h(a,c){console.log("Creating server ["+
a+"] listening on "+c)}function l(a){m++;1E6<m&&(m=0);g[m]=a;return a.applicationID=m}function a(a){a.app.broadcast.send=function(c,b,d){for(var f in g)g[f]&&g[f].applicationID!==a.applicationID&&g[f].app.broadcast.trigger(c,b,d)}}function d(d,c,b){var p=null,f=null,h=null,m="";console.log("New connection from ["+d.remoteAddress+"]");d.on("data",function(g){var k=m+g.toString();g=k.split("\n");"\n"!==k.substr(-1)&&(m=g.pop());g.map(function(g){if(!(2>g.length))switch(g=JSON.parse(g),g.a){case "x":if(c.aliases&&
c.aliases[g.w]){var m="Starting ["+g.w+"] ...";try{p=require(global.__base_path+c.aliases[g.w]),m+="OK!",f=p({send:function(a){d.write(a)},close:function(){f.app.destroyAll();d.close()}},b)}catch(k){f=p=null,m+="ERROR ["+k+"]!"}null!==f&&(h=l(f),a(f));console.log(m)}else console.log("Error: Alias ["+g.w+"] not found!");break;default:f&&f.parseRequests(g)}})});d.on("close",function(){f&&f.onClose();null!==h&&delete g[h]});d.on("error",function(){f&&f.onError();console.log("Connection ERROR!!!")})}
k.readConf=function(a,c){var b=require("fs");void 0===global.__base_path&&(global.__base_path=__dirname);b=JSON.parse(b.readFileSync(a));if(!0===c){console.log("Checking aliases...");var d,f;for(f in b.aliases){d="Trying to load alias ["+f+"]: ["+b.aliases[f]+"]...";try{require(global.__base_path+b.aliases[f]),d+="OK!"}catch(g){d+="ERROR ["+g+"]!"}console.log(d)}}return b};var g={},m=0;k.SockJS=function(a,c,b){var g=require("http"),f=require("sockjs").createServer();f.on("connection",function(b){d(b,
a,c)});void 0===b?(b=g.createServer(),f.installHandlers(b,{prefix:"/mirror"}),f=a.host,g=a.port,void 0===f&&(f="0.0.0.0"),h("SockJS",f+":"+g),b.listen(g,f)):f.installHandlers(b,{prefix:"/mirror"})};k.Socket=function(a,c){var b=require("net"),g=a.host,f=a.port;void 0===g&&(g="0.0.0.0");b=b.createServer();h("Socket",g+":"+f);b.listen(f,g);b.on("connection",function(b){d(b,a,c)})}},{}],13:[function(n,q,k){var h=n("./widgets"),l=n("./events"),a=n("./base"),d=n("./logger");k.handler=function(g,m){var e=
this,c={};this.protocolHandler=g;this.events=new l(this);this.create=function(b){var e=h.getClass(b.t);d.log("Frontend: Creating widget "+b.t+" ["+b.w+"]",d.level.LOG_DEBUG);if(void 0===e)d.log("Frontend ERROR: The widget "+b.t+" ["+b.w+"] is not installed!!!",d.level.LOG_DEBUG);else if(e=e[m],void 0===e)d.log("Frontend ERROR: The widget "+b.t+" ["+b.w+"] doesn't have the UI Handler: ["+m+"]!!!",d.level.LOG_DEBUG);else{var f=b.w,g=void 0,k=b.e;void 0===k&&(k={});void 0!==b.p&&(g=c[b.p]);var l=new a.ui(this,
f,g,k);l.type=b.t;e.call(l,this,f,g,k);c[f]=l;l.create()}};this.update=function(a){c[a.w]&&c[a.w].parseState(a.s)};this.activateEvent=function(a){c[a.w]&&c[a.w].activateEvent(a.t,a.p)};this.handleEvent=function(a){var d=c[a.w];d&&(d.__internal_events[a.t]&&d.__internal_events[a.t].call(d,a.p),d.events[a.t]&&d.events[a.t].call(d,d,a.p))};this.getCtl=function(a){return c[a]};this.destroy=function(a){c[a]&&(d.log("Frontend: Destroying widget "+c[a].type+" ["+a+"]",d.level.LOG_DEBUG),c[a].destroy(),delete c[a])};
this.destroyAll=function(){Object.keys(c).sort(function(a,c){return c-a}).map(function(a){e.destroy(a)})};this.domClassHandler=function(a,d,f){c[a]&&(!0===f?c[a].addClass(d):c[a].removeClass(d))};this.getFrontendProp=function(a,d,f,e){var g=c[a];a={a:"Fp",w:a,r:e,s:0};g&&g.props&&g.props[d]&&g.props[d].get&&(d=g.props[d].get.call(g,f),a.s=1,a.p=d);this.protocolHandler.handle([a])}};k.connectors={local:function(a,d){this.isRemote=!1;this.name=a;this.connection=d},remote:function(a){this.isRemote=!0;
this.connection=a}}},{"./base":"Vlbn99","./events":5,"./logger":7,"./widgets":"RD6lrm"}],"./widgets":[function(n,q,k){q.exports=n("RD6lrm")},{}],RD6lrm:[function(n,q,k){function h(a){function g(a){for(var b in a)e[b]={"default":a[b]["default"],type:a[b].type,description:a[b].description}}var h=new l.backend;a.backend.call(h);var e={};h.__base_props&&g(h.__base_props);h.props&&g(h.props);h=null;return e}var l=n("./base"),a={};k.getClass=function(d){return a[d]};k.map=function(d){for(var g in a)d(g,
a[g])};k.getInfo=function(d){if(a[d])return{name:a[d].name,author:a[d].author,version:a[d].version,properties:h(a[d])}};k.install=function(d){a[d.name]=d};k.installAll=function(a){var g=require("fs");void 0===a&&(a=__dirname+"/widgets");g.readdir(a,function(g,e){g||!e?console.log("ERROR: Invalid widget's path: ["+a+"]"):e.filter(function(a){return"mirror.js"!==a&&".js"==a.substr(-3)}).forEach(function(c){var b;b="Trying to install widget ["+c+"] ...";try{require(a+"/"+c)}catch(e){b+="ERROR ["+e+"]!",
console.log(b)}})})}},{}]},{},[]);var mirrorJS;(function(){"undefined"!==typeof module&&module.exports?module.exports=mirrorJSRequire("mirrorJS"):mirrorJS=mirrorJSRequire("mirrorJS")})();
